version: "3"
services:
  app:
    image: ${ECR_REPOSITORY_NAME:-test}:latest
    build:
      context: ../
      dockerfile: docker/app/Dockerfile
    environment:
      TEST: "true"
      PORT: 8080
    ports:
      - 8080:8080

